name: CI
permissions:
  contents: read
  pull-requests: write
on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint --if-present -- --quiet
    - run: npm run test --if-present -- --quiet
    - run: npm run coverage --if-present -- --quiet
