name: CI
on: [ push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2.3.0
    - run: npm install
    - run: npm run build --if-present
  Lnt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2.3.0
    - run: npm install
    - run: npm run lint --if-present -- --quiet
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2.3.0
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test --if-present -- --quiet
  Cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2.3.0
    - run: npm install
    - run: npm run build --if-present
    - run: npm run coverage --if-present -- --quiet